'use strict';
const fs=require('fs');
const assert=require('assert');
const path=require('path');
const root=path.join(__dirname,'..');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
assert(index.includes('href="./manifest.json"'));
assert(index.includes('src="./app.js"'));
assert(index.includes('href="./icon.svg"'));
assert.strictEqual(manifest.start_url,'./');
assert.strictEqual(manifest.scope,'./');
assert.strictEqual(manifest.icons[0].src,'./icon.svg');
assert(app.includes("navigator.serviceWorker.register('./sw.js')"));
assert(app.includes('state.settings.cloudAI = false'));
assert(app.includes('On-device generation'));
assert(!app.includes('Use cloud AI when available'));
assert(!app.includes('Test AI connection'));
assert(sw.includes("new URL('./',self.location.href)"));
console.log('PASS: GitHub Pages deployment checks');
